#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"; source "$SCRIPT_DIR/lib/common.sh"
usage(){ cat <<'USAGE'
Usage: scripts/install-uprm.sh PHASE [--repo PATH] [--env PATH] [--hostname HOST] [--allow-dirty] [--no-start]
Phases: check, prepare, migrate, build, install-services, verify, all.
USAGE
}
phase=check; [[ $# -gt 0 && "$1" != --* ]] && { phase="$1"; shift; }; repo="$REPO_DIR"; env_file=; hostname=; allow_dirty=false; start_services=true
while [[ $# -gt 0 ]]; do case "$1" in --repo) repo="$(realpath "${2:?}")"; shift 2;; --env) env_file="$(realpath "${2:?}")"; shift 2;; --hostname) hostname="${2:?}"; shift 2;; --allow-dirty) allow_dirty=true; shift;; --no-start) start_services=false; shift;; --help|-h) usage; exit 0;; *) uprm_die "unknown option: $1"; exit 2;; esac; done
env_file="${env_file:-$repo/.env}"; compose_file="$repo/infra/docker/docker-compose.yml"
run_check(){ [[ -d "$repo/.git" ]] || uprm_die "not a Git repository: $repo"; git -C "$repo" rev-parse HEAD >/dev/null; [[ "$allow_dirty" == true || -z "$(git -C "$repo" status --porcelain)" ]] || uprm_die "refusing dirty source tree without --allow-dirty"; "$repo/scripts/validate-env.sh" --production "$env_file"; node_version="$(node --version 2>/dev/null || true)"; [[ "$node_version" == v20.* ]] || uprm_die "Node.js v20 is required; found ${node_version:-missing}"; pnpm_version="$(pnpm --version 2>/dev/null || true)"; [[ "$pnpm_version" == 10.33.0 ]] || uprm_die "pnpm 10.33.0 is required; found ${pnpm_version:-missing}"; uprm_docker compose --env-file "$env_file" --file "$compose_file" config --quiet; printf 'install_check=passed commit=%s
' "$(git -C "$repo" rev-parse HEAD)"; }
case "$phase" in check) run_check;; prepare) run_check; (cd "$repo" && pnpm install --frozen-lockfile && pnpm --filter @uprm/db db:generate);; migrate) run_check; uprm_docker compose --env-file "$env_file" --file "$compose_file" up --detach --wait; (cd "$repo" && pnpm --filter @uprm/db db:migrate:deploy && pnpm --filter @uprm/db exec prisma migrate status --schema packages/db/prisma/schema.prisma);; build) run_check; (cd "$repo" && pnpm lint && pnpm typecheck && pnpm test && pnpm build);; install-services) [[ -n "$hostname" ]] || uprm_die "--hostname is required"; args=(--repo "$repo" --env "$env_file" --hostname "$hostname" --apply); [[ "$start_services" == true ]] && args+=(--start); "$repo/scripts/install-system-files.sh" "${args[@]}";; verify) args=(--repo "$repo" --env "$env_file"); [[ -n "$hostname" ]] && args+=(--hostname "$hostname"); "$repo/scripts/verify-installation.sh" "${args[@]}";; all) [[ -n "$hostname" ]] || uprm_die "--hostname is required for all"; dirty_arg=(); [[ "$allow_dirty" == true ]] && dirty_arg=(--allow-dirty); "$0" prepare --repo "$repo" --env "$env_file" "${dirty_arg[@]}"; "$0" migrate --repo "$repo" --env "$env_file" "${dirty_arg[@]}"; "$0" build --repo "$repo" --env "$env_file" "${dirty_arg[@]}"; "$0" install-services --repo "$repo" --env "$env_file" --hostname "$hostname"; "$0" verify --repo "$repo" --env "$env_file" --hostname "$hostname";; *) usage >&2; uprm_die "unknown phase: $phase"; exit 2;; esac
